defaults :
  - physicsnemo_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: LRstepwise
  - _self_

optimizer:
  lr: 0.0005
  
scheduler:
  decay_rate: 0.97
  decay_steps: 20000

training:
  rec_results_freq : 10000
  rec_constraint_freq: 10000
  max_steps : 2500

batch_size:
  inlet: 2000
  outlet: 2000
  initial: 3000
  wall: 3000
  interior: 5000
  num_integral_continuity: 5
  integral_continuity: 8000
